### ISSUE TITLE
A Note on Brave Connectivity: WS connections

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/substrate-connect#1016]
https://docs.talisman.xyz/talisman/help-and-support/troubleshooting/balances-on-brave-not-showing

I suspect connect will also run into issues with restricted WS connections. After knowing is this is the case, use facing notifications about hoe to update like Talisman provides should be implemented.

**Comment by tomaka** [comment]
Integrating WebRTC would normally solve this.
https://github.com/paritytech/smoldot/issues/1712

**Comment by wirednkod** [comment]
Closing this in favour of #1178  and #1179
