### ISSUE TITLE
Extension should display, next to each chain, the current best block number of that chain

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#1029]
When you look at the list of chains in the extension, you should see the current best block in small somewhere next to each chain.
And this best block number should update in real time.

The objective is to show to the user that things are live and moving.

However this shouldn't be shown too big, so as to not give the impression that this information is important, because this number is not something that the average Joe needs to understand.

**Comment by wirednkod** [comment]
Fixed with #1082
