### ISSUE TITLE
Popup Extension buglist

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#1073]
Below are @Goranch3 's comments concerning the popup of extension that should be fixed:
- [x] Remove shadow from substrate-connect logo
- [x] "Options/Settings" and "About" Icons should have tooltips declaring what they are (exact text tbp)
- [x] When Tabs are connected in the popup they should be open by default as it is not clear from the icon
- [x] Remove white background of connected tabs
- [x] "Disconnect" should convert to an icon (since its only 1 option)
- [x] Remove the white background on "connected networks" and align with the logo names above
- [x] <del>Pointer of link should be a link pointer</del> Apparently one cannot navigate from extension to a tab - thus this task changes to just "Remove the link-like color of connected app"
- [x] All icons (on the right) should be aligned 
- [x] <del>Empty state when tabs are not connected to the network</del> Dropdown icon indicates the existence of tabs
- [x] Hover shadow of About is not nice and needs alignment
- [x] Check that all gaps/margins are aligned

**Comment by Goranch3** [comment]
https://www.figma.com/file/s8KFS3Anf7Wfk2axp8UdUY/Substrate-Connect-Extension-01?node-id=35%3A520
