### ISSUE TITLE
Rename smoldot-extension

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#111]
As suggested by @Stefie in #92 

I would rename the project to something other than smoldot-extension to not start the next batch of confusion, though.
It's a substrate-connect extension, smoldot delivers the Wasm Light Client, but the extension should behave the same no matter if the Light client is generated by smoldot or maybe Substrate or Polkadot one day.
The smoldot-provider makes 100% sense since that's a wrapper especially for smoldot, bur for all demo apps it doesn't matter where the Light Client is coming from, therefore I'd not name applications after it.

**Comment by raoulmillais** [comment]
Maybe we could go even further and just call it "extension"?  are we likely to have more than one browser extension

**Comment by Stefie** [comment]
That's open for discussion. 
One of the initial ideas was to build a single use extension as a demo and then merge it back into Polkadot JS extension once the Light Client is fully functional. But that was half a year ago when syncing still took days (literally) and the extension was needed to interact with the light client without waiting >24h by keeping a synced database of the connected node.

Now we can have more product oriented extensions like: One for Bridges, one for Polkadot Governance notifications etc.
Or we put all functionality into one Light Client Extension.

I'd tend to No. 1, product oriented extensions, but I don't have strong opinions on it at this point.

**Comment by raoulmillais** [comment]
Yeah - good point about product-focussed extensions. I tend to agree too :+1: This extension could stay having the sole responsibility of being the extension responsible for managing blockchain clients and the apps connected to them - other (product-focussed) extensions could connect to it just as we're envisaging regular web pages will.

I think merging back into PolkadotJS extension is a bad idea: it has a very different security model because it holds private keys so minimising what it does is a good thing. Not-to-mention that affects its UX - you have to authorise it for every use in an app. Something substrate-connect probably doesn't want.

**Comment by raoulmillais** [comment]
It is now just called "extension"

**Comment by wirednkod** [comment]
That was just a decision of the moment. We should keep this open until we finalize the name (so we do not forget that eventually we need to name the extension :) )
