### ISSUE TITLE
List of apps not refreshed properly

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#1110]
![image](https://user-images.githubusercontent.com/1412254/174060163-dbbf09b2-b566-4c0f-ab81-b36629b77cca.png)

By connecting/disconnecting I can arrive at this state where there's only one app but the list shows two.
Closing and reopening the window fixes it, so it's most likely a problem of things not getting refreshed.

**Comment by wirednkod** [comment]
I cannot replicate this is Firefox.
Can you please provide version of extension, browser used etc?

**Comment by tomaka** [comment]
- Open the options page
- Open a tab to https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fpolkadot#/explorer (Polkadot)
- Then in that tab, go to https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fkusama#/explorer (Kusama)
- Then go to https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fpolkadot#/explorer (Polkadot)
- Then go to https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fkusama#/explorer (Kusama)
- Then go to https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fwestend#/explorer (Westend)

You'll see "Polkadot (1)" but with two tabs in the list.

**Comment by tomaka** [comment]
You even arrive to some funny results if you continue switching:

![image](https://user-images.githubusercontent.com/1412254/174496684-9160d03a-87e3-438a-b1f3-07aa62fcafe7.png)

**Comment by wirednkod** [comment]
Note: As it seems this happens ONLY in firefox (not in chrome) and only if the tab that is open switches client. Once the tab closes, everything gets back to normal.

**Comment by wirednkod** [comment]
This is strange - as it is not reproducible while running `apps` application locally, but only when deployed.

**Comment by wirednkod** [comment]
Since version 1.0 of smoldot this issue does not appear anymore (tested in latest Firefox). Please reopen if issue still exist
