### ISSUE TITLE
importing rpc-provider to SvelteKit causes error

### ISSUE THREAD

**Issue by hitchhooker** [paritytech/substrate-connect#1137]
```
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/satoshi/code/chaostool/node_modules/.pnpm/@substrate+connect@0.7.7/node_modules/@substrate/connect/dist/index.js from /home/satoshi/code/chaostool/node_modules/.pnpm/@polkadot+rpc-provider@8.10.1/node_modules/@polkadot/rpc-provider/cjs/substrate-connect/ScProvider.js not supported.
Instead change the require of index.js in /home/satoshi/code/chaostool/node_modules/.pnpm/@polkadot+rpc-provider@8.10.1/node_modules/@polkadot/rpc-provider/cjs/substrate-connect/ScProvider.js to a dynamic import() which is available in all CommonJS modules.
```
```
	import { ScProvider, WellKnownChain } from '@polkadot/rpc-provider/substrate-connect';
```
importing scprovider causes error.
```
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.8",
		"@lukeed/uuid": "^2.0.0",
		"@polkadot/api": "^8.10.1",
		"@polkadot/keyring": "^9.6.2",
		"@polkadot/rpc-provider": "^8.10.1",
		"cookie": "^0.5.0"
	}
```
i just followed the docs to use lightclient instead of wsprovider but seem to be hitting errors. any tips for fix?

**Comment by wirednkod** [comment]
@hitchhooker thank you for the issue.

ScProvider and alll `@polkadot/rpc-provider/substrate-connect` only support ES Modules (ESM) so you will need to use import instead of `require()` to import those into your packaging. You can do that by adding `type: "module"` into your package.json and convert your code accordingly.

**Comment by hitchhooker** [comment]
confusing since thats exactly how my package.json is setup and receiving this error. also using only import commands instead of requires.
like this feels specific issue for sveltekit/vite

```
devdeps
...
		"vite": "^2.9.8"
	},
	"type": "module",
	"dependencies": {
		"@fontsource/fira-mono": "^4.5.8",
		"@lukeed/uuid": "^2.0.0",
		"@polkadot/api": "^8.3.1",
		"@polkadot/keyring": "^9.1.1",
		"cookie": "^0.5.0",
		"svelte-slider": "^1.0.1"
	}
```

**Comment by wirednkod** [comment]
Hey @hitchhooker we try to add dual (CJS and esm) support to substrate connect, as can be seen [here](https://github.com/paritytech/substrate-connect/pull/1142), and after some tests (Im not familiar at all on how `sveltekit` works),   I have high hopes that once the PR is merged and the new version is released in `@polkadot/rpc-provider/substrate-connect`, you will most-likely be able to use is with `svelteKit`.
The screenshot below shows that `substrate-connect` integrated into the sample To-Do app built with svelte (App appears in extension and in console I manage to print all latest headers:

  
![image](https://user-images.githubusercontent.com/5408605/177857747-13a306b6-f6d1-4930-a8bc-73ac244f73ad.png)

**Comment by wirednkod** [comment]
Works with latest @substrate/connect (0.7.9).
You can find also an example running with substrate-connect in  `@polkadot/rpc-provider` [here](https://github.com/wirednkod/substrate-connect-sveltekit) (once you have svelte up and running, open browser console, and you will see the hashes appearing from light client)
