### ISSUE TITLE
Panic issue with browser demo

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#115]
When trying to run the browser demo following error appears:
```
index.js:93 Uncaught Error: panicked at 'called `Result::unwrap()` on an `Err` value: Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `AuthoritySet::authority_set_changes`" }', src/chain_spec/light_sync_state.rs:45:18
    at throw (index.js:93)
    at :1234/<anonymous>:wasm-function[376]:0x66b6f
    at :1234/<anonymous>:wasm-function[103]:0xbeaf
    at :1234/<anonymous>:wasm-function[2877]:0x23eb97
    at :1234/<anonymous>:wasm-function[2868]:0x23e58f
    at :1234/<anonymous>:wasm-function[2867]:0x23e558
    at :1234/<anonymous>:wasm-function[2876]:0x23eab1
    at :1234/<anonymous>:wasm-function[2944]:0x24560e
    at :1234/<anonymous>:wasm-function[2967]:0x2491e4
    at :1234/<anonymous>:wasm-function[1226]:0x10129c
```

**Comment by raoulmillais** [comment]
Cc @tomaka

**Comment by tomaka** [comment]
v0.1.12 doesn't work anymore with chain specs with an older checkpoint.
Please use [this](https://github.com/tomaka/test-browser-node/blob/master/dist/westend.json), or remove the `lightSyncState` key from the JSON altogether.

**Comment by wirednkod** [comment]
Thank you @tomaka

**Comment by raoulmillais** [comment]
I did this here @wirednkod - https://github.com/paritytech/substrate-connect/pull/112/commits/67dfa84e8f7abac29bbf7d3eca64c85a355bc773 I suspect this heppening for you because your browser is returning a cached version of the chain spec, I have an issue for that already here https://github.com/paritytech/substrate-connect/issues/113

**Comment by raoulmillais** [comment]
Thanks @tomaka - I'm going to close this. Should I open a smoldot issue about making it more defensive when receiving an invalid chain spec?
