### ISSUE TITLE
Add CI tests for supporting UI bundlers

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#1172]
There should be CI tests for testing support of latest react/node bundlers:
- webpack
- parcel
- vite

**Comment by tomaka** [comment]
This would require adding **a lot** of code to this repo, and I'm honestly not sure that it's worth the trade off.

**Comment by wirednkod** [comment]
> This would require adding **a lot** of code to this repo, and I'm honestly not sure that it's worth the trade off.

Not really... Its just 1 extra "project" as can be seen [here](https://github.com/wirednkod/substrate-connect-bundlers-test).
The only extra are the configs of the bundlers and the [builds run for same simple files](https://github.com/wirednkod/substrate-connect-bundlers-test/runs/7537434117?check_suite_focus=true).

[CI tests](https://github.com/wirednkod/substrate-connect-bundlers-test/blob/main/.github/workflows/main.yml) all bundlers by reusing the code and just grabbing different configuration
