### ISSUE TITLE
Mixed licenses

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#119]
The licenses are a different and inconcsistent even in the same context:
* The root license file is GPL3 but the root package.json says Apache-2.0
* The newly added projects / packages are Apache2. (I just copied the Burnr license, but is that right?) 
* Smoldot is GPL3.  

Which is the correct one to use?  Is it the same for all or different? (categorised below to make it easier to comment)
* PolkadotJS API provider
* Browser extension 
* Product demos: burnr and smoldot-browser-demo

**Comment by goldsteinsveta** [comment]
@kirushik could you help here? are you the right person?
