### ISSUE TITLE
Replace publishing github action 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#1215]
Based on [this PR](https://github.com/paritytech/substrate-connect/pull/1214)  a bug bounty researcher found that the publish GH action contains a broken reference to a non-existent user. @sergejparity already patched that issue but there is a need of either remove completely or replace that action with a more secure one.

**Comment by douglasday** [comment]
Fix looks good @wirednkod !

Thanks for the fast turnaround!

- Douglas Day
