### ISSUE TITLE
Extensions crashes after sometime using it - smoldot error message

### ISSUE THREAD

**Issue by filippoweb3** [paritytech/substrate-connect#1225]
On multiple occasions and on multiple devices the extension crashed. The only way of restoring it is to delete it from the browser and re-install it. While crashing there is also a smoldot error message on the UI.

<img width="364" alt="Screenshot 2022-08-22 at 15 50 57" src="https://user-images.githubusercontent.com/110459737/185937604-8d158e24-0a94-4202-b160-aaf000472fc2.png">

**Comment by wirednkod** [comment]
An error message has been added with #1228
