### ISSUE TITLE
`Error while creating the chain: Received RPC message while chain isn't ready yet` 

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#1233]
With the extension enabled, I was connected to the "GM" parachain through the PolkadotJS light client, then switched to the "Tinkernet" parachain, and got this error.

**Comment by wirednkod** [comment]
Please provide browser used (Chrome or Mozilla), and logs prior to the error one, if possible

**Comment by wirednkod** [comment]
Closing this as there is no update for 3 weeks and bug has not been reported since. If this occurs again please reopen and attach logs.
