### ISSUE TITLE
Local node doesn't reconnect after system goes to sleep mode

### ISSUE THREAD

**Issue by Asmadek** [paritytech/substrate-connect#1243]
When I close my laptop and open it again node doesn't reconnect to network. But ScProvider instance says that everithing is OK, doesn't show any error. Reconnect provider and api doesn't help here.
 
You can test it here [https://paritytech.github.io/substrate-connect/demo](https://paritytech.github.io/substrate-connect/demo/)

1. Open page
2. Wait untill it will be connected
3. Close laptop or move PC to sleep mode
4. Open laptop
5. Block number will not update anymore

**Comment by pgolovkin** [comment]
@wirednkod Please take a look at this issue.

**Comment by wirednkod** [comment]
@Asmadek can you please provide more logs on this?

**Comment by pgolovkin** [comment]
@wirednkod There is a log that I'm getting when roll up the window and then restore it.
[localhost-1663154196134.log](https://github.com/paritytech/substrate-connect/files/9565802/localhost-1663154196134.log)

**Comment by Asmadek** [comment]
@wirednkod excuse me, link for test app was wrong. Can you check my issue again. 

I tested it with extension and without. In both cases situation the same. No special logs, only this messages after few minutes of waiting. 

```
logger.js:62 2022-09-14 16:58:00        RPC-CORE: subscribeRuntimeVersion(): RuntimeVersion:: Disconnected
logger.js:62 2022-09-14 16:58:00        RPC-CORE: subscribeNewHeads(): Header:: Disconnected
```

**Comment by wirednkod** [comment]
Thank you @Asmadek .
Hopefully there will be a PR in the next few hours about this.

**Comment by wirednkod** [comment]
[This](https://github.com/polkadot-js/api/pull/5217) is now merged.
