### ISSUE TITLE
Westend light client connection stuck at block #14.192.193 due to forceApprove

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/substrate-connect#1376]
Due to an operational issue on the Westend validators at Parity, we had to execute a [sudo initializer.forceApprove operation at block #14192316](https://westend.subscan.io/extrinsic/14192316-2) to recover consensus.

This has the consequence of breaking substrate-connect for this network. We apologize for the inconvenience.

**Comment by wirednkod** [comment]
@PierreBesson what are the corrective actions and solution that should be taken for network to work again in Substrate-Connect?

**Comment by PierreBesson** [comment]
I tried to look for information in this issue tracker on how the problem was handled last time it happened but couldn't find anything. My intuition is that we it should be enough to create a newer checkpoint file.

**Comment by wirednkod** [comment]
A newer checkpoint release should be created. I was trying to make sure that there are no more details missing. Thank you Pierre.
