### ISSUE TITLE
Upgrade the smoldot version (current 1.0.13)

### ISSUE THREAD

**Issue by Douglasacost** [paritytech/substrate-connect#1554]
### Is your feature request related to a problem? Please describe.

If possible upgrade the internal smoldot version on the extension, since the last release is 2.0.1 against the current implemented on the extension 1.0.13

### Describe the solution you'd like

Use latest smoldot release

### Additional context

The issue present is, Dapps with majors smoldot version temp to crash while switching to use the extension instead of the embedded node. 

Somehow the `forceEmbeddedNode` is not working

**Comment by wirednkod** [comment]
Thank you @Douglasacost . I will close this here since the extensions has been updated with [this PR](https://github.com/paritytech/substrate-connect/pull/1566)
