### ISSUE TITLE
Force approve executed on Westend block #17956291

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/substrate-connect#1594]
See: https://westend.subscan.io/block/0xb42bf3867cfaf24ac0c9f0b3b90dc47eb58cacd26b84a50d8648af56e52c9a69

Similarly to the situation described in #1376, we had to execute a force_approve today to restore finalization on Westend. This will require a new checkpoint on substrate-connect to restore light client functionality.

[EDIT] I just tried the light-client and it seems to still be working https://polkadot.js.org/apps/?rpc=light%3A%2F%2Fsubstrate-connect%2Fwestend#/explorer

@wirednkod do we still need to ping you for these kind of situations ?

**Comment by josepot** [comment]
Hi @PierreBesson ! Thanks for letting us know 🙏.

I'm closing this b/c this hasn't caused any changes that require for a new chainspec.
