### ISSUE TITLE
It seems to work in the background but nothing shows up.

### ISSUE THREAD

**Issue by thiolliere** [paritytech/substrate-connect#1823]
After having visiting polkadot app: https://cloudflare-ipfs.com/ipns/polkadot.dotapps.io

The extension seems to do some work in the background but nothing shows up:

here an image of the extension:
![image](https://github.com/paritytech/substrate-connect/assets/10416848/d6690b01-f6f0-453e-84ad-09cc4bb2776f)

here an image of the extension console:
![image](https://github.com/paritytech/substrate-connect/assets/10416848/f4fbd4de-d68f-495d-9fef-ad1d07afc218)

Is it syncing or is there a bug? maybe it would be better to report the syncing is on-going.

I tested on both chrome and firefox with same result

**Comment by josepot** [comment]
Currently the PJS Apps are using an old version of `@substrate/connect`, which is not compatible with the extension. Therefore, until that gets addressed, using the light-client with the PJS Apps is like using it without the extension, meaning that a dedicated instance of smoldot is used for the DApps.

In other words: this issue belongs into the [PJS Apps repo](https://github.com/polkadot-js/apps)

**Comment by thiolliere** [comment]
thank you,

Maybe the doc of substrate-connect could list some supported apps so I could have test out my setup.
