### ISSUE TITLE
Burnr demo's transfers are not working

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#1827]
### Issue Description

When trying to send to the burnr wallet in Westend, the funds never arrive (tested from polkadotJS extension);
When trying to send from the burnr wallet to another account an error appears:
`Uncaught (in promise) TypeError: pt.tx.balances.transfer is not a function`

### Steps to reproduce the issue

Steps to reproduce the issue
1. open burnr account with funds
2. open polkadot js apps on a westend account with funds
3. send from each account to the other

### Describe the results you received

When trying to send to the burnr wallet in Westend, the funds never arrive (tested from polkadotJS extension);
When trying to send from the burnr wallet to another account an error appears:
`Uncaught (in promise) TypeError: pt.tx.balances.transfer is not a function`

### Describe the results you expected

Funds should be transfered without error between accounts

### Substrate-Connect version

latest

### Provider

Chrome

### Browser version

Version 121.0.6167.139 (Official Build) (arm64)

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

### Screenshots

![Screenshot 2024-02-07 at 23 47 13](https://github.com/paritytech/substrate-connect/assets/5408605/212d5b3d-995f-40ad-b3b4-a2f8ae968851)
![Screenshot 2024-02-07 at 23 47 23](https://github.com/paritytech/substrate-connect/assets/5408605/cd1f330d-e37f-467f-8c36-38cdbffc9280)

**Comment by ryanleecode** [comment]
was able to reproduce. looking into it.

![image](https://github.com/paritytech/substrate-connect/assets/21375952/a8b11630-77d1-4445-a7e3-d4583743df93)

**Comment by wirednkod** [comment]
@ryanleecode is there a deployed solution that works?

I just tested the deployed version and it is still not working:

![image](https://github.com/paritytech/substrate-connect/assets/5408605/a92cf41e-e6d7-47bb-9c79-466a20f65ad2)

**Comment by kratico** [comment]
Thanks for the follow up @wirednkod 
We'll release a new version of substrate-connect which will later require a new release of PJS with this new substrate-connect version.

On PAPI, Could you upload an example to https://stackblitz.com/ with the issue?

**Comment by wirednkod** [comment]
Hey @kratico . I was expecting a follow up from your side.
Concerning PAPI, I tried to run the demos inside the repository - which do not seem to work

**Comment by kratico** [comment]
Once https://github.com/polkadot-js/api/pull/5817 is released then we need to upgrade PJS in the Burnr project and deploy.

@wirednkod regarding PAPI I don't see any issues.
Zombienet and Playwright tests are working in CI with PAPI.
I did a local sanity test and I didn't see any issues too.
I could be something related your environment.

**Comment by wirednkod** [comment]
@kratico The issues I had was with the version that I tested [during this comment](https://github.com/paritytech/substrate-connect/issues/1827#issuecomment-1991488403). 
[You released a new one and then mentioned](https://github.com/paritytech/substrate-connect/issues/1827#issuecomment-1991522372) that everything works fine - which confused me event more. Make sure that you mention after a  new version is released in order to recheck issues

**Comment by kratico** [comment]
Sorry for the confusion @wirednkod 
I thought that with [this](https://github.com/paritytech/substrate-connect/issues/1827#issuecomment-1991522372) comment, it was clear that a new release was coming up.

**Comment by wirednkod** [comment]
It did - but next comment sounded like there is nothing still updated. Just tested Burnr and it works
