### ISSUE TITLE
Issue with smoldot Worker with CI tests (jest)

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#185]
There is an issue when Jest tests run that need smoldot client.
When smoldot client initialises (through smoldot Provider tested so far), during test coverage some logs coming form [smoldot-js] appear:

<img width="1176" alt="Screenshot 2021-03-24 at 9 53 43 AM" src="https://user-images.githubusercontent.com/5408605/112274216-e925b180-8c86-11eb-8459-2e0c31173de3.png">

At the end of the tests the following message appears:
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
```
Even though the test pass fine the above issue do not allow CI to finish.

When jest runs with --detectOpenHandles to find leaks the following error appears:
<img width="947" alt="Screenshot 2021-03-24 at 9 55 25 AM" src="https://user-images.githubusercontent.com/5408605/112274456-2d18b680-8c87-11eb-9195-e9c20ff5c09b.png">

**Comment by wirednkod** [comment]
Related comments:
https://github.com/paritytech/substrate-connect/pull/179#discussion_r600485429
https://github.com/paritytech/substrate-connect/pull/179#discussion_r600488990

**Comment by tomaka** [comment]
I believe this was fixed by https://github.com/paritytech/smoldot/pull/1710 and https://github.com/paritytech/substrate-connect/pull/559

It turns our that on NodeJS, `Worker.terminate` is asynchronous (contrary to browsers where it's not) and we weren't waiting for the promise to be finished to end the test.
