### ISSUE TITLE
Export `WellKnownSystemChains`

### ISSUE THREAD

**Issue by josepot** [paritytech/substrate-connect#1911]
### Is your feature request related to a problem? Please describe.

I think that System Chains (AKA "common good chains") chainspecs from the `@substrate/connect-known-chains` package.

### Describe the solution you'd like

I propose exporting them from `@substrate/connect-known-chains` with the following names:

```ts
export const polkadotAsssetHub: string = '...';
export const polkadotBridgetHub: string = '...';
export const polkadotCollectives: string = '...';

export const westend2AsssetHub: string = '...';
export const westend2BridgetHub: string = '...';
export const westend2Collectives: string = '...';

export const ksmcc3tAsssetHub: string = '...';
export const ksmcc3BridgetHub: string = '...';

export const rococo_v2_2AsssetHub: string = '...';
export const rococo_v2_2BridgetHub: string = '...';
```

So that system-chains can be easily available.

**Comment by ryanleecode** [comment]
https://www.npmjs.com/package/@substrate/connect-known-chains/v/1.1.0
