### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/substrate-connect#2055]
- [ ] Document Polkadot Provider spec; must live in the substrate connect repo
- [ ] Document the "Multi Injected Provider" spec

**Comment by jsdw** [comment]
On reflection, I think we can get away with some documentation like:

# Building a compatible extension

A compatible extension has two parts to it:

1. It is discoverable using the XXX discovery mechanism. This means that it will show up when YYY function is called within a dapp [I think we have a library function that dapps can use to do this discovery already for YYY? Link to the relevant EIP if we are 100% following it in XXX]
2. The interface returned when the above discovery takes place matches the PolkadotProvider interface shown in ZZZ [link to the polkadot provider repo, ideally to some documentation of the interface or the actual .ts file if nothing suitable]

The template extension provided in AAA conforms to both of these, and is a good starting point for building your own wallet extension.

**Comment by ryanleecode** [comment]
Marking this as done
