### ISSUE TITLE
Disconnect apps when the extension is uninstalled

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#229]
During testing I have realised that when the extension gets uninstalled / suspended there is malfunctioning on existing opened tabs. 
This needs to be addressed by enriching the content/background scripts with listeners per life cycle of the extension.

**Comment by raoulmillais** [comment]
Depends on #234

**Comment by raoulmillais** [comment]
Is this still valid @wirednkod

**Comment by wirednkod** [comment]
@raoulmillais - yes it is. IMO when extension is removed or suspended then "disconnect" should be sent to all open tabs that contain a uApp. No actions are needed when extension is installed as any open tab will be already connected through SmoldotProvider

**Comment by raoulmillais** [comment]
Ah yeah ... good point :+1:

**Comment by tomaka** [comment]
It seems to me that the content script will continue running if you install the extension, which means that the ports would close, and errors will be generated as expected.

Should be tested before closing this issue, though.

**Comment by wirednkod** [comment]
Tested and the following error appears on the app when extension is uninstalled while app is running:
```
Uncaught CrashError: Extension has killed the chain: Lost communication with substrate-connect extension
```
