### ISSUE TITLE
Allow UI to disconnect apps

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#234]
The UI should be able to disconnect an app by using its `tabId`.  We would like this to be graceful from the apps perspective. As things are currently implemented if we simply disconnect all the ports an app has open then extension provider won't know about it and will just carry on sending RPC messages to the content script which it can't process - there would probably loads of errors in the console for that app.  To do this properly we need to do the following:

* [x] Implement a `disconnectTab` method on the ConnectionManager to disconnect all the apps by `tabId`.  `disconnectTab` will call:
* [x] a new `disconnect` method on all the `AppMediator`s with the `tabId` supplied.  This method should perform the same logic as if the port had closed normally.  It should:
  * Call `disconnect` on the port 
  * Unsubscribe from all the subscriptions 
  * Wait for the responses 
  * Make sure the state is updated and emit the `stateChange` event
* [x] Add a new optional `disconnect` property to the `ExtensionMessage` and make the `message` optional.
* [x] Add a handler in the `ExtensionMessageRouter` to handle the port being disconnected to send a new "disconnected" message with `window.postMessage` to the `ExtensionProvider` in the app to tell it that the port has closed
* [x] Handle the "disconnected" message in the `ExtensionProvider` to change its internal state and emit `disconected` so the app can react to it if it wants to.
* [ ] Bump the @substrate/connect and @substrate/connect-extension-protocol versions

**Comment by raoulmillais** [comment]
(migrated from element) @wirednkod said:
> Sounds a bit overengineering but I have not given much if a thought so far
> Once u remove injected tag from tab id, close.port and refresh tab then its like extension does not exist for that tab
So extension provider closes

@raoulmillais  said 
> yeah it does, but I dont think we should be refreshing an app's tab ... it might be doing other things unrelated to the connection to the network .. its kinda "impolite" to do that to the app

I think the story " We might tell you we've disconnected you at any time. You should be able to respond to that" is much more palatable to an app developer than the story "We might refresh the tab your application is running in at any time".

There's a whole myriad of things apps might be doing that are unrelated to their connection to the extension.  We cannot know what the impact is on an application of us refreshing the tab.  Here's a concrete example: an app might be querying data on the blockchain and streaming data back over a websocket to a service

**Comment by wirednkod** [comment]
We should not force refresh the tab - and you are right on that. Instead we should keep a list of apps that have been disconnected (suspended) in order to disallow them from reconnecting until the switch is back to enabled.
If user though refreshes his uApp then it will again connect to the extension and a loop is created.

For both scenarios of "disconnect" or "suspend/reactivate" a uApp on extension - I believe a needed list of allowed/disallowed apps should exist inside background (AppsMediator maybe can take care of it - or a simple flag on each app called "allowed" defaulting to true when app is connected).

**Comment by raoulmillais** [comment]
> For both scenarios of "disconnect" or "suspend/reactivate" a uApp on extension - I believe a needed list of allowed/disallowed apps should exist inside background (AppsMediator maybe can take care of it - or a simple flag on each app called "allowed" defaulting to true when app is connected).

It's definitely needed for suspend / reactivate but not for just disconnecting an app.

> if disconnect - remove the app

yeah that's what im outlining above

To get the suspend behaviour working as you imagined it in our meeting I think we also need to change the detector to fallback to `SmoldotMediator` in the case where the extension is installed but the app has been suspended

**Comment by wirednkod** [comment]
>It's definitely needed for suspend / reactivate but not for just disconnecting an app.

It can be reusable for both scenarios. This way with 1 implementation you can grasp both scenarios (for v0 and later stage)

> To get the disable/enable behaviour working as you imagined it in our meeting I think we also need to change the detector to fallback to SmoldotMediator 

How will you inform the detector that app is disconnected and it needs to fallback to SmoldotMediator without keeping a list of "disconnected" apps?

**Comment by raoulmillais** [comment]
Ok I think we are talking about a few different points here, I see disconnecting and enabling/disabling as orthogonal behaviours:

* Being able to disconnect apps doesn't need to know anything about whether an app is enabled or not... it is just disconnecting an already connected (enabled) app.

* Disabling an app that is currently running involves both disconnecting that app and remembering that the user has disabled it to prevent it connecting to the extension again until the user re-enables it.

* In order to have the behaviour that a disabled app attempting to connect to the extension falls back to the SmoldotProvider we would have to make changes to the detector... The detector cannot know currently that it has been disabled.  It detects the extension exists but it fails to connect because the extension won't allow it.  I'm also unclear as to whether that is the right behaviour in the scenario that an end-user (not a developer testing) disables an app.... In my mind if they disable an app they probably expect it to stop connecting to blockchains. cc @goldsteinsveta

**Comment by raoulmillais** [comment]
So saying this I'm more clear in my mind that building the enable / disable functionality for a developer who is testing their extension is not the right thing to do.  I think the developer testing scenario is adequately covered by the developer disabling the extension entirely to test how their app behaves.  Trying to account for a developer who has multiple apps open only one of which they are testing is just too niche IMO.

**Comment by raoulmillais** [comment]
> We should not force refresh the tab - and you are right on that.

Given this ... I think I can just get on with implementing "disconnecting". Whatever we decide about implementing enable / disable for apps this logic will be needed and I'm fairly confident what I proposed doesn't prohibit / hamper any of the discussed scenarios.

**Comment by goldsteinsveta** [comment]
ok so how about interfacing this like:

<img width="800" alt="Screenshot 2021-04-21 at 13 11 41" src="https://user-images.githubusercontent.com/8782596/115545480-25f3c100-a2a4-11eb-848c-6c6b4c8c00f9.png">
<img width="800" alt="Screenshot 2021-04-21 at 13 13 03" src="https://user-images.githubusercontent.com/8782596/115545484-27bd8480-a2a4-11eb-8ada-d67d0d04cf97.png"><img width="800" alt="Screenshot 2021-04-21 at 13 20 48" src="https://user-images.githubusercontent.com/8782596/115546840-cdbdbe80-a2a5-11eb-8304-453689f8587a.png">

- In the Popup, little 'x' button to block (disconnect) the uApp and a link to the list of blocked uApps. The number of blocked uApps is there mainly to indicate the effect of pressing the little 'x' button, not necessary for its own sake. I can imagine merging the Networks and Blocked uApps into a single Settings once there's more than 3-4-5 things to set up
- In the Options, there's a list of blocked uApps. Items have date when they were blocked and a little 'x' button to unblock them. Options Menu is a new thing here
- Oh yeah, the word "block" is also a part of UI for discussion. As I understand this will have a permanent effect on the app and the block is better at signalling this

**Comment by raoulmillais** [comment]
This looks good @goldsteinsveta I really like the "block" terminology and change from a toggle to a single click and a separate blocked apps page - it feels more direct and obvious what is going on :thumbsup:  Having a UI mock-up also makes it much easier to think about what needs to be implemented.
