### ISSUE TITLE
[BUG] Extension modify `$` global object

### ISSUE THREAD

**Issue by tien** [paritytech/substrate-connect#2390]
### Issue Description

The extension modify the page global `$` object, breaking any web page that used it (any page that used JQuery).

### Steps to reproduce the issue

Install the extension.

### Describe the results you received

`$` is replaced with a `Set<string>`.

### Describe the results you expected

No global object will be modified.

### Substrate-Connect version

0.6.0

### Provider

Firefox

### Browser version

129.0b9

### Screenshots

<img width="460" alt="image" src="https://github.com/user-attachments/assets/d14b3d64-1b5e-45a0-9ea6-3799d887fa3f">

**Comment by ryanleecode** [comment]
This is strange behaviour. Investigatng now.

**Comment by ryanleecode** [comment]
@tien how are u getitng a set with chainhead methods in it

im seeing this

![image](https://github.com/user-attachments/assets/a0e0460e-6955-49be-9973-888c17b0f151)

**Comment by ryanleecode** [comment]
Seems to work here as well

https://www.w3schools.com/jquery/trysel.asp

![image](https://github.com/user-attachments/assets/1ceee3fa-aea3-4013-a926-c7bb9bfc3f2d)

**Comment by tien** [comment]
I'm getting this with the version currently in production, both Firefox and Chrome. I couldn't reproduce this when building the extension from the repo and running it.

**Comment by ryanleecode** [comment]
Nothing has really changed in the extension so it should work the same. I'll do another release and we will see if that fixes it.

**Comment by ryanleecode** [comment]
Yeah so it does happen even in a new release. But not locally in dev mode :thinking:

**Comment by tien** [comment]
Okay I've found the issue, production code was being minified, turning some variables name into `$`, which will break the page because currently `inpage.js` is being injected via a `script` tag as a classic script, leaking all variables into the global scope.
