### ISSUE TITLE
Unrecognised message type from extension undefined

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#241]
ExtensionProvider.ts:104 Uncaught (in promise) Error: Unrecognised message type from extension undefined
    at ExtensionProvider.<anonymous> (ExtensionProvider.ts:104)
    at ExtensionProvider.ts:185

**Comment by raoulmillais** [comment]
I think this was fixed a while ago as part of another issue.  I reordered and improved the messages in this code.  Feel free to reopen if it appears again
