### ISSUE TITLE
Installation instructions in readme outdated

### ISSUE THREAD

**Issue by bjornwgnr** [paritytech/substrate-connect#260]
i.e. `$ substrate-connect % yarn dev:smoldot-extension` fails with:

```
yarn run v1.22.0
yarn workspace @substrate/smoldot-extension run dev
error Unknown workspace "@substrate/smoldot-extension".
```

Workspace names appear to have changed. I.e. `@substrate/smoldot-extension` --> `@substrate/extension`

**Comment by wirednkod** [comment]
@bjornwgnr thank you for that
