### ISSUE TITLE
Tidy up downloading specs for tests

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#295]
The script to download the specs from the upstream smoldot repo is copy/pasted in 2 places (extension and connect).  This should only be in one place (probably the root) and should happen post-build in the root package.json so that the latest specs are available for the tests but so that they aren't needlessly redownloaded again and again before every build in either connect or extension.  Also since we are fetching them from upstream and don't control them they should probably be gitignored as they add distracting diffs to pull requests arbitrarily.

**Comment by wirednkod** [comment]
The issue that we may have if we move the downloads to one place (root) is what will happen if one tries to build only specific project/package.
Following two examples:
- run: `yarn workspace @substrate/connect run build` or `yarn workspace @substrate/extension run build` (which of course are not commands of root `package.json` but still valid commands);
- someone enters directory of connect or extension and runs `yarn run build`
In these 2 examples the json files will not download (will not exists as they will be in `.gitignore`) and thus build/test will fail.

As agreed with @raoulmillais will proceed with having separate scripts inside each project (mainly `connect` and `extension`) that - if someone decides to run them separately (as per examples above)  - then one has to run these steps first (guidelines will be added in each separate project's README file).

**Comment by wirednkod** [comment]
Closed due to #377
