### ISSUE TITLE
Where can i reading about build wasm node  for light client ?

### ISSUE THREAD

**Issue by zababurinsv** [paritytech/substrate-connect#300]
Please tell me. Where can you read how to make your wasm files with glue code js for substarte ?

**Comment by raoulmillais** [comment]
What exactly are you trying to achieve?  The easiest way to use the light client is by using @substrate/connect from npm (which is what this project is for).  @substrate/connect provides you with a [PolkadotJS API](https://polkadot.js.org/docs/) instance that uses a WASM light client.   But I warn you at the moment you should consider this software extremely alpha. We have not announced it and are still testing heavily.  That said we have working demos and integrations, so feel free to experiment at your own peril!

If you are only interested in building and inspecting the WASM client and not having a usable API for building a DApp then you can take a look at [smoldot](https://github.com/paritytech/smoldot/) which is the rust codebase which we compile the WASM light client from.  The Javascript glue code and build can be found [here](https://github.com/paritytech/smoldot/tree/main/bin/wasm-node/javascript).  Smoldot is not substrate or polkadot.  It is a completely new implementation of a blockchain client / runtime environment specifically designed with light clients in mind, it should support most substrate-based chains however.  You can see more information in the README.
