### ISSUE TITLE
Current JSON-RPC API not really suitable for light clients

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#317]
Write up the issue(s) we are facing with the mismatch between polkadotjs API and the light client use-case to start a discussion with Jaco.

* We want to be able to have a usable API instance earlier than the client being synced - smoldot can actually respond to many requests fine when the client is not synced
* Unpick some of the 'connectedness' assumptions if possible
  * No need for a health pinger in polkadotjs when using a light client
  * Retry behaviour is different (not applicable) for light clients
* Handle TrieRootNotFound errors more gracefully

@tomaka - if you have some ideas about what you think polkadotjs API should really be doing when storage is not available could you pop them down as a comment in this issue please?

**Comment by tomaka** [comment]
> if you have some ideas about what you think polkadotjs API should really be doing when storage is not available could you pop them down as a comment in this issue please?

What I have in mind is that the PolkadotJS UI should present a warning to the user explaining that the state of the chain is currently inaccessible, and then periodically re-tries.

**Comment by tomaka** [comment]
We've decided to fix this by creating a brand new JSON-RPC API: https://github.com/paritytech/json-rpc-interface-spec/

While there's not much that can be done in substrate-connect about this, I think it's not a bad idea to leave this issue open in order to remember that this effort exists.

**Comment by tomaka** [comment]
Closing because there's no actually anything actionable.
