### ISSUE TITLE
CI should run all the tests

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#325]
I can't remember why they were disabled but we should definitely have CI running all the tests as a priority

**Comment by wirednkod** [comment]
After a day of narrowing down one by one the tests the outcome is slightly disappointing (By this I mean - that I managed to pinpoint tests that create the issues (and what issues each)):
- `SmoldotProvider.tests.ts`: 
     a) test('emits connect and never emits disconnect for development chain') [Test run](https://github.com/paritytech/substrate-connect/runs/2840814654?check_suite_focus=true)
     b) test('emits events when it connects / disconnects / reconnects')
     -> These two tests are not allowing Jest to exit with error message: `"Jest did not exit one second after the test run has completed. This usually means that there are asynchronous operations that weren't stopped in your tests.`

- `Detector.tests.ts`:
   a) tests with actual actual chains (polkadot, kusama, westend)
     ->  Several times CI tests ends with timeouts as networks take longer to respond during tests (more than 35 seconds each) ending up to `Jest did not exit one second after the test run has completed`
     [Test run 1](https://github.com/paritytech/substrate-connect/runs/2840728393?check_suite_focus=true), [Test run 2](https://github.com/paritytech/substrate-connect/runs/2839769513?check_suite_focus=true)
     -> Other times it would lead to the `terminate() has been called` error [Test run](https://github.com/paritytech/substrate-connect/runs/2837801386?check_suite_focus=true)

- `api.tests.ts`:
    Tests were leading randomly to`Jest did not exit one second after the test run has completed`

   -> Note: Error `FATAL ERROR: v8` appeared several times when having `api.tests.ts`. Never appeared again when they were removed [Test run](https://github.com/paritytech/substrate-connect/runs/2827850404?check_suite_focus=true)

When all of the above are removed CI tests run correctly
