### ISSUE TITLE
Integrate smoldot cancelAll functionality

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#327]
We can simplify the `AppMediator` by removing the subscription tracking / disconnecting logic in favour of using this new smoldot feature.  <del>This is currently blocked</del> There is an intermittent bug in smoldot affecting this functionality. @tomaka can you link to the relevant issue if there is one please?

**Comment by tomaka** [comment]
It's not blocking, the bug happens rarely.

https://github.com/paritytech/smoldot/issues/814

**Comment by wirednkod** [comment]
`CancelAll` has been removed from smoldot v3 and as a result this issue should close.

Unless I am missing something @raoulmillais ?
