### ISSUE TITLE
Setup a trustworthy source for downloading chainspecs

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#337]
Chainspecs are the most obvious vector of attack for a substrate client.  Since we are bundling the specs with @substrate/connect we should stop pulling them from the smoldot repo and instead have an internal process that can generate the chainspecs with a new checkpoint and then validate that when using them smoldot syncs to a block that is actually part of the chain, for example by cross-checking using PolkadotJS connected to one of the Parity RPC server nodes.

**Comment by wirednkod** [comment]
As agreed with @tomaka , Chainspecs will exist in the same repo so this can close
