### ISSUE TITLE
Fix extension zip placement during deployment 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#339]
There is a bug that does not allow the extension's zip to be placed on github pages and/or ipfs:
```
Place Substrate-connect extension's zip.
cp: cannot stat './projects/extension/dist/substrate-connect.zip': No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
https://github.com/paritytech/substrate-connect/runs/2843533854?check_suite_focus=true

**Comment by raoulmillais** [comment]
Did you forget to build the extension zip before running the deployment?

**Comment by wirednkod** [comment]
> Did you forget to build the extension zip before running the deployment?

No manual actions here. Build command of extension does (or at least should do) it automatically:
```
$ webpack --config webpack.prod.js && zip -r ./dist/substrate-connect.zip ./dist/*
```

**Comment by wirednkod** [comment]
Will close this in favor of #344 (contains thezip placement as part of tasks)
