### ISSUE TITLE
Transfer table stopped working

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#346]
The transfer table stopped showing (through localstorage) the transfers that take place. This is probably a bug that was created due to various merges,

**Comment by wirednkod** [comment]
This is actually working fine. The transfer table would work if wallet receives from an update of what happens to the transfer sent (related to [paritytech/smoldot#480](https://github.com/paritytech/smoldot/issues/480)).

Once there is update on the transfer status then transfer will be saved in LocalStorage and will show in Transfers screen

cc @tomaka

**Comment by wirednkod** [comment]
After upgrade of Smoldot to 0.2.9 which makes `Broadcasted` and `InBlock` do work. At the same due to `error` the errored transaction was input to localstorage and Transfer table. Based on feedback from @tomaka due to some finality not-properly-working issue in smoldot, substrate-connect will not at this moment receive any `Finalized` status.
This is the status, though, that once received will write the transaction to local storage.

Will remove the `bug` label, add a `retest needed` one,  keep this issue open and lower the priority - and will retest once finality is fixed in smoldot.

cc @raoulmillais

**Comment by raoulmillais** [comment]
Bump @wirednkod

**Comment by wirednkod** [comment]
This is still not working cause the all transfers for Westend are identified as dropped. I think this is probably relevant to the new specs that we dont have them included yet.

![dropped2](https://user-images.githubusercontent.com/5408605/128675701-f29f30cd-bf82-426a-8995-c2b745d36b5d.png)
![dropped-polakdotjs](https://user-images.githubusercontent.com/5408605/128675702-b9278121-65d5-4d7b-a9a5-5fc44ff939ff.png)


cc @tomaka
