### ISSUE TITLE
Extension package installation/unpack

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#355]
Need to create an easy way for users to download and unpack/install the extension even from [landing page](https://paritytech.github.io/substrate-connect/).

**Comment by wirednkod** [comment]
Extension now exists on chrome and mozilla stores so this can close

**Comment by tomaka** [comment]
I suggest we close once there's indeed links to the extensions in the landing page and/or elsewhere. Right now it's still not easy to install it.

**Comment by wirednkod** [comment]
@tomaka There are [links](https://github.com/paritytech/substrate-connect/blob/master/projects/landing-page/src/App.tsx#L277-L282)) for stores in the landing page. Just not deployed yet
