### ISSUE TITLE
Update Extension designs

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#360]
Update Extension designs for:
- Options page: show the known apps and chain specs (and their correlation)  as per #359 
- Permission dialogue (trust check): A pop up that will request consent from user in order to trust or not the incoming unknown to the extension app

**Comment by goldsteinsveta** [comment]
Hey @wirednkod! Lmk wdyt!

Options #359:

<img width="1520" alt="Options - Allowed Apps" src="https://user-images.githubusercontent.com/8782596/125614085-f115a5c1-eab8-4fdd-9a90-80181996dcc3.png">
<img width="1520" alt="Options - Networks" src="https://user-images.githubusercontent.com/8782596/125614103-d87804c9-0dc3-45e2-919b-55aed2337608.png">

Popup:

<img width="880" alt="Popup" src="https://user-images.githubusercontent.com/8782596/125614226-48c86164-d3f2-45c8-b868-aba461cc070a.png">

Dialogue:

<img width="880" alt="Dialogue" src="https://user-images.githubusercontent.com/8782596/125614265-f35de42e-6452-4826-8d95-c2aa8bb0d902.png">

<img width="841" alt="Screenshot 2021-07-14 at 13 10 04" src="https://user-images.githubusercontent.com/8782596/125614282-310fa524-c2fd-4852-9b10-a8968fd19ecd.png">

**Comment by wirednkod** [comment]
@goldsteinsveta This looks good. 
I do not think we need to show/see the chainspecs though (this `url.net/../chainspec.json` field)

**Comment by goldsteinsveta** [comment]
@wirednkod I meant this as a link, not field. You won't ever want to check the chain spec file?

**Comment by wirednkod** [comment]
> @wirednkod I meant this as a link, not field. You won't ever want to check the chain spec file?

As far as I understood from our last conversation that is not needed. We can leave it on the design for now and remove it on later stage (or not implement it).

**Comment by goldsteinsveta** [comment]
@wirednkod yeah, we discussed that it will be somewhat complicated and unnecessary for Options - Networks, but not for the trust check dialogue. Anyhow, can I close the issue?

**Comment by goldsteinsveta** [comment]
@wirednkod I've updated screens in the previous comment!
