### ISSUE TITLE
Get alerted when polkadotjs API is released

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#369]
so that we can update @substrate/connect and publish an update as soon as possible.  There is an example [here](https://github.com/peter-evans/create-pull-request/blob/master/docs/examples.md#update-swaggerui-for-github-pages) of how to automatically open pull requests when a 3rd party repository has a new release.  This coul deasily be adapted for our needs.

**Comment by tomaka** [comment]
This no longer needed after https://github.com/paritytech/substrate-connect/pull/554

It would still be nice to upgrade quickly, but this would be covered by https://github.com/paritytech/substrate-connect/issues/548
