### ISSUE TITLE
Landing page sidebar wraps oddly when not fullscreen

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#370]
![2021-06-23_10:57:55](https://user-images.githubusercontent.com/302663/123077368-e6676380-d411-11eb-9997-5010fcd3e174.png)

When it is not fullscreen the sidebar jumps to the top, but it obscures the content and with the new "API documentation" link wraps onto a new line.  THis happens on both firefox and chrome

**Comment by wirednkod** [comment]
@raoulmillais This is for more "mobile views" the smaller the width of the screen the more menu items will wrap. If the screen is large enough, items will be on one line.
One thing we could do (and probs make sense) is to hide the menubar completely once in mobile mode.
