### ISSUE TITLE
Receive error on api connect: "Unrecognised message type from extension info "

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#401]
When using extension with apps application, while trying to retrieve the api from detector the following error appered:
```Unrecognised message type from extension info ```

![Screenshot from 2021-07-07 17-19-07](https://user-images.githubusercontent.com/5408605/124776048-ce323100-df47-11eb-911a-8da885742862.png)

**Comment by wirednkod** [comment]
This exists now in polkadotJS

![unrecognized message type](https://user-images.githubusercontent.com/5408605/126640784-382d315f-f5f6-4460-b094-455be4fa299e.png)

**Comment by raoulmillais** [comment]
This is fixed by #434

**Comment by wirednkod** [comment]
Closed based on [comment above](https://github.com/paritytech/substrate-connect/issues/401#issuecomment-894175804)
