### ISSUE TITLE
Fix the AppMediator states

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#443]
We make an `AppMediator` 'connected' immediately.  It doesn't start sending RPC messages to smoldot until it has received a `'spec'` message and `smoldotClient.addChain()` has resolved successfully.  We should add a new 'connecting' state and transition to 'connected' appropriately when `addChain` has resolved

**Comment by wirednkod** [comment]
As per #572 the `AppMediator` seized to exist so this should close
