### ISSUE TITLE
Chrome Extension page not showing 

### ISSUE THREAD

**Issue by sacha-l** [paritytech/substrate-connect#465]
I've installed the `substrate-connect` packages, now following the instructions for running the Smoldot Extension, I run:

```bash
yarn clean && yarn install
yarn dev:smoldot-extension
```
It runs successfully in my terminal but no new Chrome page appears. This may be something I need to tweak in my Chrome settings? Thanks!

**Comment by wirednkod** [comment]
When you run the `yarn dev:extension` command (chrome version) you need to add the extension manually to your browser. 
You can follow the steps:
- write on your address bar: `chrome://extensions/`
- make sure the `Developer Mode` is activated (top right)
- Click `Load unpacked` (top left)
- Navigate and open the directory `substrate-connect-repo/projects/extension/dist`

The extension should be now installed

**Comment by sacha-l** [comment]
Got it working ! Thanks @wirednkod. 🙏🏻
