### ISSUE TITLE
Make the bootnodes of the well-known chains configurable from the extension

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#492]
Right now all the "well known chains" (the chains whose chain specs can be found in this repo) use bootnodes hosted by Parity.

However, it's important to note that Parity is providing these bootnodes as a service, and that it should in no way be mandatory for users to use *these* bootnodes in particular. Anyone can host their own bootnodes and put their addresses in the chain spec.

In order to be in line with this, it is important for users of the extension to have a way to configure the list of bootnodes of the chains whose specs are hardcoded in the extension.

For the same reason, the `substrate-connect` library on NPM (the one containing the `Detector` and `SmoldotProvider`) should also not contain any bootnode.

**Comment by tomaka** [comment]
This requires us to store in the local storage the list of bootnodes overwritten by the user.

If a list of bootnodes is found in the local storage, then we should replace the `bootnodes` field of the well-known chain specs (westend, rococo, polkadot, kusama) with that list. If no list of bootnodes is found, then do nothing and straight up pass the chain specs.

When the user modifies this list of bootnodes in the UI:
For each entry in the list, call a JSON-RPC method on the smoldot chain which doesn't exist yet (:warning:) mostly to make sure that the syntax is correct. Add the entry to the final list (the one stored in the local storage) only if the JSON-RPC method is successful.

If smoldot returns an error when initializing a well-known chain, erase the list of bootnodes from the local storage and try again. Even though we try to only add valid entries to the local storage in the first place, we don't want a chain to fail to load if the user somehow fucks up their local storage.

**Comment by tomaka** [comment]
> call a JSON-RPC method which doesn't exist yet (warning)

That would be `sudo_v1_p2pDiscover`.
(link, which will probably be dead in a few weeks: https://paritytech.github.io/json-rpc-interface-spec/api/sudo_unstable_p2pDiscover.html)

**Comment by wirednkod** [comment]
This can be closed in favour of #981 . 
Solution is implemented in #1128 that is pending review
