### ISSUE TITLE
Docs for `ExtensionPageInjector` not rendering

### ISSUE THREAD

**Issue by sacha-l** [paritytech/substrate-connect#497]
Noticed that for some reason TypeDoc isn't rendering the docs [here](https://paritytech.github.io/substrate-connect/api/classes/_substrate_extension.extensionpageinjector.html#constructor) for `ExtensionPageInjector`.

**Comment by raoulmillais** [comment]
That class doesn't exist anymore.  We're also no longer publishing API docs for the extension as it isn't intended to be consumed by external developers.  You can still read the docs in the comments in the code of course.
