### ISSUE TITLE
Smoldot - crash strategy

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#507]
We need to have a strategy when a smoldot crash happens.
Probably, when this occurs, we should disconnect the apps from the chain, inform the UI (emit?) of the App and/or the extension and re-start smoldot.

**Comment by tomaka** [comment]
As a heads up, this can be done by catching a `CrashError` when calling any of the methods of smoldot:
https://github.com/paritytech/smoldot/blob/409ea559fa7fddfccd79c4f000def8f0e81bd350/bin/wasm-node/javascript/src/index.d.ts#L43.

I would suggest doing all of this in `index.ts`.

**Comment by tomaka** [comment]
cc https://github.com/paritytech/substrate-connect/issues/429#issuecomment-1059754226

**Comment by ryanleecode** [comment]
#1786
