### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#523]
Based on current case there is a need of end to end integration tests.
Proposed solutions are:
a) Use <del>docker</del> zombienet for bundling a test ui with substrate connect and smoldot and a substrate node
b) Use <del>docker</del> zombienet for bundling a test ui with substrate connect and smoldot and existing Westend

In scenario (a) the tests will be more autonomous and run irrelevant to the current state of Westend (this also adds extra values for having docker image for demos/presentations etc.

**Comment by wirednkod** [comment]
Instead of docker, [zombienet](https://github.com/paritytech/zombienet) is be used (updating the description accordingly).
There is an [ongoing effort](https://github.com/paritytech/substrate-connect/pull/668) with @pepoviola for this.

**Comment by wirednkod** [comment]
This can close now as #706 is merged

**Comment by raoulmillais** [comment]
Closing since you said it could be closed @wirednkod

**Comment by tomaka** [comment]
We do have integration tests, but they're not great. Could either do a new issue and re-close this one, or leave this one open.

**Comment by wirednkod** [comment]
Integration test is implemented with Zombienet - more complicated tests can be added, but IMO a new issue should be introduced
