### ISSUE TITLE
Set up CI for uApps in ./projects

### ISSUE THREAD

**Issue by Stefie** [paritytech/substrate-connect#55]
Open issue in https://github.com/paritytech/ci_cd/issues?page=2&q=is%3Aissue+is%3Aopen

**Comment by raoulmillais** [comment]
* [ ] Configure linting for all projects / packages and run `yarn lint` on all projects
* [ ] Run `yarn build` on all projects
* [ ] Add a (possible noop) `yarn test` to all projects and run it as part of CI

**Comment by wirednkod** [comment]
@raoulmillais can you elaborate on the nightly(?) trigger?

**Comment by wirednkod** [comment]
Solved by #134
