### ISSUE TITLE
Deploy multiple apps to gh-pages and ipfs

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#57]
### Deploy any subproject and have a landing page in the root to show a "catalogue" of the apps

* [ ] Reorganise/check current yarn scripts

In the repository root `package.json`:

When triggering deploys from the root of the folder you're unlikely to only want to deploy to ipfs or gh-pages. so always deploy both for a project. Ie. delegate to `yarn deploy` in that project's folder

A one-click deploy script to deploy everything isn't sensible - it'd be easy to accidentally deploy more than you intended and you're more likely thinking about deploying a single project .   If you want to deploy everything it's not that much more effort when deploying to do:

1. `yarn deploy:landing`
2. `yarn deploy:burnr`
3. `yarn deploy:smoldot-browser-demo`
4. `...`

If you're adding a new project then you do:

1. Add new project in projects folder
2. Add new project to landing page
3. `yarn deploy:landing`
4. `yarn deploy<news-project>`

In the child projects `package.json`:

Separate scripts - in case you need to solve a broken deployment to only one of the  targets (ipfs/gh-pages).  I.e.

`yarn deploy`   - deploys to both and is called by the root package.json
`yarn deploy:ipfs`
`yarn deploy:gh-pages`

* [ ] Add landing page 

I suggest that a landing page should be a special type of "project" to make the mechanics of the shared deployment scripts simple.

It's easier not to deploy the landing page to IPFS initially and tackle that as a separate issue if we think we want to.  Beacuse if we deploy an app the link on the landing page stays the same but it does not for IPFS (because it has a different hash).  We can solve that by using [IPNS](https://docs.ipfs.io/concepts/ipns/#example-ipns-setup-with-cli) but that's quite a bit more work and probably overkill at this early stage.

I.e. put the landing page in `projects/landing`

* [ ] Change deploy scripts to work for any project in the project folder

Yarn scripts will rely on consistent use of `yarn build` in subprojects to produce a deployable folder in `dist` in that project (as is currently the case for burnr and smoldot-browser-demo).

Special case for landing page - does not go into a subfolder in the resulting deployment

* [ ] Change deploy script to deploy into subfolders on gh-pages
* [ ] Change ipfs deploy script to update hash links in landing page

**Comment by raoulmillais** [comment]
@Stefie (from #47)
>I would just assume that we need to update all apps when we're introducing any significant changes to the @substrate packages, there are changes to the @polkadot packages, Smoldot or even Substrate, so instead of triggering the updates all manually , there would be one command to deploy all.

See above for my thinking

**Comment by Stefie** [comment]
> See above for my thinking

There's no right or wrong in that regard. We should just try to keep the versions of the @polkadot packages aligned throughout the problems to prevent yarn.lock conflicts & nightmares.
I used the `yarn workspace @substrate/... add module` syntax to then be able to for example run `yarn workspaces upgrade @polkadot`
