### ISSUE TITLE
Modify the `Background` interface to be more precise

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#571]
The interface defined [here](https://github.com/paritytech/substrate-connect/blob/bfaf68b2d96f5f02702f97f0d8f6ad17c0004720/projects/extension/src/background/index.ts#L5) is too loose.

It should give access to the strict minimum of information that the extension needs, like the list of chains with their name and health.
In particular, we shouldn't expose the `ConnectionManager`.

**Comment by tomaka** [comment]
To clarify: this `interface` should only expose getters/functions that use primitive types in JavaScript, or interfaces that use only primitives types.

The objective is that this interface should be completely abstract.

**Comment by josepot** [comment]
Addressed on #656
