### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by KaiserKarel** [paritytech/substrate-connect#593]
## Context
We'd love to use substrate-connect for our parachain, but it seems to not be entirely ready for that yet. We're open to contributing to get it to that state. Adding the discussions tab to this repository allows for a nice thread for teams to see what the state of the project is, and who is tackling what.

## Advantage
No need to create issues like this one, which pollute the tracker.

**Comment by tomaka** [comment]
Done!
