### ISSUE TITLE
SmoldotProvider - Make events behave like other providers

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#60]
Consumers of the `SmoldotProvider` have no way of knowing that we failed to start syncing from bootnodes because eg. we are offline.  We need to simulate as closely as sensible what the `WsProvider` does in this case  so that the consumer can chose to show an offline UI.  

These `connected` `disconnected` and `error` events are [propagated](https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L65-L67) to the `Api` instance so we want the following to work as expected:

```
const provider = new SmoldotProvider(chainSpec());
const api = await ApiPromise.create({ provider });
api.on('error', () => /* do something */);
api.on('connected', () => /* do something */);
api.on('disconnected', () => /* do something */);
```
### Behaviour with WsProvider 

Consumers of `WsProvider` listen to the 3 events: `error`, `connected` and `disconnected` : 
* If `WsProvider` fails to connect to its remote node it only emits `error`.  Consumers can optionally `connectWithRetry`
* If it connects without error it emits `connected`. 
* If later the socket is closed it emits `disconnected`.  

(It also has logic for trying other remote nodes but that's not relevant for a smoldot client.)

### Approach

Set an interval pinger after instantiating the smoldot client to send an RPC `system_health` message to check the `peers` count. 

### Desired behaviour

* Don't emit `connected` until we see `peers > 0` from `system_health` pinger
* Emit `disconnected` if peer count from `system_health` drops back to zero after having previously been `> 0`

* Emit `error` if the `system_health` request responds with `peers == 0` right after after instantiating the smoldot client (analagous to error connecting on startup)
* Emit `error` if the `system_health` request responds with an error.
* Do something similar to `connectWithRetry` on the `WsProvider` https://github.com/polkadot-js/api/blob/master/packages/rpc-provider/src/ws/index.ts#L188-L201 but rather than acutally `reconnecting` we delay reporting the `error` event until a threshold time period is elapsed.  

**Aside**

The Api has its own pinger for `system_health` [used to keep the websocket alive](https://github.com/polkadot-js/api/blob/master/packages/api/src/base/Init.ts#L332-L342).  Unfortunately we cant get at the responses it receives from the provider so we have to redundantly have a second pinger in the provider.

 See https://github.com/paritytech/smoldot/issues/435 for a longer conversation.

**Comment by tomaka** [comment]
Sorry to reopen the discussion :see_no_evil: 

> Emit error if the system_health request responds with peers == 0 right after after instantiating the smoldot client (analagous to error connecting on startup)

It is *always* going to be `peers == 0` right after instantiating. The promise returned by `startClient` is ready as soon as the Wasm engine starts. All the initialization of smoldot and connecting to peers is done in the background.

If there is an error in smoldot (which is never supposed to happen), it's going to be reported as an error log, which you can catch and report as an error event.
If `peers` stays at 0 and no error is reported in the logs, it simply means that there's no Internet connectivity or that all bootnodes are down (and it's not really possible to differentiate between these two situations anyway).

Maybe something that confuses you is that 502 errors when connecting don't produce any error log. It is intended that they do produce an error in the logs.

**Comment by raoulmillais** [comment]
Yep I 'm pretty sure do understand this and your concerns now, so let me restate to clarify a little and with some extra background about PolkadotJS API.

I believe that the Provider abstraction in PolkadotJS is wrong (or more accurately hadn't considered fully this new future usecase)... PolkadotJS makes an assumption that all providers go through an initial connect phase that might error (if they fail to connect as well as if something unexpeted happens) and that they then emit `connect` and `disconnect` lifecycle events.  That assumption permeates through the API related classes and in the way `Provider`s and API are intended to be used.

These assumptions however don't make sense for a light client where the contract is:
1. It will initialise and either return an initialised client or error (in the case of some bug, but this shouldn't happen).  I.E. There is no notion of connecting in this process.
2. It simply reports how many peers it has via the `system_health` RPC call.  Again iI does not expose any notion of being connected or not. That is handled internally *by design* in the smoldot client and the consumer is not supposed to care about it.

What I am trying to do  in the `SmoldotProvider` is mimic the behaviour of the `WsProvider` and `HttpProvider` .. I.E. trick PolkadotJS and users that the SmoldotProvider behaves just like the other providers by simulating this "connecting" and "disconnecting and "erroring on failure to first connect" behaviour when really it doesn't.
 
This hackery almost certainly won't stand the test of time and will no doubt confuse other people as it has me when they have to change this code.  So ideally we would rework The `Api` classes and `ProviderInterface`s to isolate the connection state logic and where it is relied on and have a smaller Provider interface without the baggage of those connection-related assumptions, which captures only the commonality of providers related to sending and receiving RPC messages.

> Sorry to reopen the discussion see_no_evil
> 
> > Emit error if the system_health request responds with peers == 0 right after after instantiating the smoldot client (analagous to error connecting on startup)
> 
> It is _always_ going to be `peers == 0` right after instantiating. The promise returned by `startClient` is ready as soon as the Wasm engine starts. All the initialization of smoldot and connecting to peers is done in the background.

I was thinking that the first peer count check should happen after the first interval ping triggered (for example after 2seconds) and where I said "Do something similar to `connectWithRetry` on the WsProvider" I was thinking that I would overload `connect` with an optional timeout parameter in ms to allow the consumer to choose how long to wait before considering the smoldot client offline.

> 
> If there is an error in smoldot (which is never supposed to happen), or a protocol error when connecting to the bootnodes (which again is never supposed to happen), it's going to be reported as an error log, which you can catch and report as an error event.
> If `peers` stays at 0 and no error is reported in the logs, it simply means that there's no Internet connectivity or that all bootnodes are down (and it's not really possible to differentiate between these two situations anyway).
> 
> Maybe something that confuses you is that 502 errors when connecting don't produce any error log. It is intended that they do produce an error in the logs.
