### ISSUE TITLE
General functionality - Keep NodeSelector visible when api connection fails

### ISSUE THREAD

**Issue by Stefie** [paritytech/substrate-connect#62]
Right now the `NodeSelector` is part of the `Head` component which is only getting rendered, when the api is initialized and connected.
The `NodeSelector` should always be getting rendered so that the user can choose a different provider if the connection is failing. It still needs to be aware of the api's connection status to be able to show that as the colored dot connection indicator:
<img width="313" alt="Screenshot 2021-02-03 at 11 46 12" src="https://user-images.githubusercontent.com/125398/106736216-76e50900-6615-11eb-874a-7c1613f77194.png">

**Comment by wirednkod** [comment]
@Stefie This is also on my To-Do list.
 When - e.g. - selecting local polkadot network and there is nothing running - everything gets stuck and in order to correct - you need to either clear cache or run a local node. I want to add some error handling on this as well - so I assigned it to me.

**Comment by Stefie** [comment]
I just started to add tickets with smaller tasks that I'm coming across. Feel free to add the things on your todo list as tickets, too! 
Makes things more visible for everyone
