### ISSUE TITLE
Identify solution for manifest v3 and wasm-eval

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#620]
Based on [this](https://bugs.chromium.org/p/chromium/issues/detail?id=1173354) discussion apparently wasm does not work in extensions manifest v3.

Manifest v2 updates will be supported until January 2023 based on [Chrome's roadmap](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/)

**Comment by tomaka** [comment]
Relates to https://github.com/paritytech/substrate-connect/issues/549

**Comment by wirednkod** [comment]
#882

**Comment by wirednkod** [comment]
Related for the solution #549 #882 
init PR: #1272
