### ISSUE TITLE
Finish implementing possibility to ban tabs from the extension

### ISSUE THREAD

**Issue by tomaka** [paritytech/substrate-connect#738]
- [ ] Add some sort of button in the UI next to each non-well-known chain.
- [ ] Keep a list of banned URLs, so that the next time someone visits, or if the user reloads the page, it's still disabled.
- [ ] Have a proper error message sent to the web page, and not just "lost connection to extension".
- [ ] Add a way in the UI to unban web pages.

**Comment by wirednkod** [comment]
As discussed before this will not be implemented
