### ISSUE TITLE
New "client" based API for accessing the `ProviderInterface`

### ISSUE THREAD

**Issue by josepot** [paritytech/substrate-connect#742]
We've realized that exposing the `ScProvider` class is not the best way to return a polkadotJs `ProviderInterface`, it would be much better to have an API that looks like the API of the `getConnectorClient`.  The interface of the new API would look like this:

```ts
import { WellKnownChains } from "@substrate/connect"
import type { ProviderInterface } from "@polkadot/rpc-provider/types"

declare function createScClient(displayName?: string): {
  addWellKnownChain: (name: WellKnownChains) => Promise<ProviderInterface>,
  addChain: (chainSpec) => Promise<ProviderInterface>
} 
```

A contrived example of its usage:
```ts
async function createProviders(
  myParachainSpec: string,
  myOtherParachainSpec: string,
): Promise<[ProviderInterface, ProviderInterface]> {
  const scClient = createScClient("myContrivedApp")
  await scClient.addWellKnownChain("polkadot")

  return await Promise.all([
    scClient.addChain(myParachainSpec),
    scClient.addChain(myOtherParachainSpec)
  ])
}
```

A few remarks and observations about this new API::
1) The exported `ProviderInterface` will eagerly connect, this is already the default behavior when creating a polkadotJs Provider like the `WsProvider`. However, since constructors can't be `async`, there is no way to detect whether the connection was successful. With the API that we are proposing OTOH it's possible to `catch` the possible errors that can happen while initializing the connection.
2) With this API it will be possible to group the related connections under the same client. Which means that now the user is responsible for creating this connections in the right order. For instance, if they want to connect to a parachain, they first must create the connection to its relayChain.
3) The optional `displayName` may be used for debugging purposes, but it doesn't have any other value apart from that. It's possible that in the future we will improve the `connect-extension-protocol` to accommodate for this field when creating a new chain, so that the connections can be grouped on the UI of the Extension. However, that effort is not part of the scope of this issue.

**Comment by tomaka** [comment]
> The optional displayName may be used for debugging purposes, but it doesn't have any other value apart from that.

I'd suggest passing a configuration object to `createScClient`, and one of the fields can be `displayName`. We probably want more options in the future.

**Comment by josepot** [comment]
> > The optional displayName may be used for debugging purposes, but it doesn't have any other value apart from that.
> 
> I'd suggest passing a configuration object to `createScClient`, and one of the fields can be `displayName`. We probably want more options in the future.

What if for the moment we don't pass anything and once we have actual stuff that we can use, then we decide on whether it should be an object or whatever? TBH It feels a bit silly to put something in the API that we know it's not going to be used yet, when it's possible to change that API without making any breaking changes.
