### ISSUE TITLE
Issue on first ignite of wallet

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#75]
Issue appears with:
```
Uncaught TypeError: "list" argument must be an Array of Buffers
    at Function.concat (index.js:399)
    at pbkdf2Sync (pbkdf2.js:18)
    at pbkdf2Encode (encode.js:21)
    at mnemonicToMiniSecret (toMiniSecret.js:26)
    at Keyring.createFromUri (keyring.js:236)
    at Keyring.addFromUri (keyring.js:182)
    at createLocalStorageAccount (utils.ts:35)
    at App.tsx:38
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
```

**Comment by wirednkod** [comment]
Error appears on:
```
const pair = new Keyring({ type: 'sr25519', ss58Format: 2}).addFromUri(mnemonic, { name: uniqueNamesGenerator(config) }, 'sr25519');
```
It appears even if:

I replace addFromUri -> addFromMnemonic, (```const pair = new Keyring().addFromMnemonic(mnemonic, { name: 'Joe Doe' }, 'sr25519');``` )
I remove nameGenerator and use plain string: 'Joe Doe'
use all defaults instead of passing configuration.

**Comment by raoulmillais** [comment]
This happens every time (even after refreshing) in Firefox.  I have latest Firefox (85.0)

**Comment by wirednkod** [comment]
> This happens every time (even after refreshing) in Firefox. I have latest Firefox (85.0)

The PR https://github.com/paritytech/substrate-connect/pull/79 that was merged earlier today fixes partially the issue. Merge from master, remove your localstorage and retry. If localstorage is "corrupted" from previous code - then it wont work

**Comment by raoulmillais** [comment]
Not on Firefox for me.   After clearing local storage and hard refeshing I cannot load burnr, even after subsequent refreshes.  Chrome now loads first time without errors when the localStorage is empty.

**Comment by wirednkod** [comment]
> Not on Firefox for me. After clearing local storage and hard refeshing I cannot load burnr, even after subsequent refreshes. Chrome now loads first time without errors when the localStorage is empty.

Just checked it - and you are right. Will have a look to it at once. Thank you

**Comment by wirednkod** [comment]
This is fixed along with PR: https://github.com/paritytech/substrate-connect/pull/83
