### ISSUE TITLE
Handle substrate-connect/smoldot errors in Burnr wallet

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#840]
At the moment if substrate-connect/smoldot thorws an error,  burnr wallet still shows the loader and there is no indication that an  error occured.
This should be handled, and a relative error should be shown

**Comment by tomaka** [comment]
It's not "if smoldot crashes", but "if an error event is generated" in the `ProviderInterface`.

**Comment by wirednkod** [comment]
Closing here - added link into #1040
