### ISSUE TITLE
Popup - create UI components as seen on FIGMA 

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#92]
- 1 common component for each network (configuration file maybe?)
- 1 component for each open tab
![Screenshot 2021-02-09 at 5 02 00 PM](https://user-images.githubusercontent.com/5408605/107383236-7955d000-6af9-11eb-80ba-50e908e079a9.png)

**Comment by wirednkod** [comment]
Parent: #93

**Comment by wirednkod** [comment]
Parent issue: #93

**Comment by goldsteinsveta** [comment]
updated, less busy
<img width="335" alt="Screenshot 2021-02-09 at 16 53 56" src="https://user-images.githubusercontent.com/8782596/107389839-6cd07800-6af7-11eb-9112-7f44df95f65f.png">
