### ISSUE TITLE
Allow users to set the maxLogLevel

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#965]
when users run into trouble with smoldot we have no way of asking them to capture more detailed logs from smoldot.  we need a way to control the smoldot `maxLogLevel` when creating a client.  E.g. #964

**Comment by tomaka** [comment]
This is _not_ about passing a `ClientOptions`, and indeed you cannot pass a `ClientOptions`. This is only about configuring `maxLogLevel`.

The options that you pass to `createSmoldotScClient` are a completely different thing than the options you pass to smoldot. Do as if they were completely unrelated and that the fact that they would both contain `maxLogLevel` should be considered a happy little coincidence.

**Comment by raoulmillais** [comment]
Yeah that's an approach I'd already considered about but it doesn't change anything I've said above .. we still end up with weirdness in the API when `createScClient` is called twice with different options

**Comment by raoulmillais** [comment]
If we do want to allow people to pass in a different `maxLogLevel` I think we also have to tell people not to call `createScClient` more that once (and maybe even remove the reference counting and throw instead for multiple calls)

**Comment by tomaka** [comment]
Users should be able pass a `logCallback` and `maxLogLevel` to `createScClient`.
Then you pass a log callback to smoldot, and this callback dispatches logs to the various log callbacks that have been registered.
If no `logCallback`/`maxLogLevel` is provided when calling `createScClient`, then it goes to `console`

**Comment by tomaka** [comment]
Actually, it's more appropriate to pass these to `addChain` so that the moment when the logs stop corresponds to removing the chain

**Comment by raoulmillais** [comment]
We can't add these to `addChain` the `logCallback` and the `maxLogLevel` can only be specified when the client is created .. this is the problem I'm referring to ... we instantiate the client once and cache it and reference count it.  There's no way to have different options for different chains as things stand

**Comment by raoulmillais** [comment]
Maybe I need to restate things to make it clearer.  At the time `addChain` is called it's too late to say what logging options substrate connect has already initialised the smoldot client with the logging options.  If we modify `createScClient` to allow specifying logging options those logging options can only be honoured the first time that function is called because it caches the instance of the smoldot client.  That IMO is very surprising to the developer because it violates the expected contract - "i gave this functions some options the second time I called it: why were they ignored"

**Comment by tomaka** [comment]
> it might be too late to say what logging options because substrate connect might have already initialised the smoldot client with the logging options for a previous call of addChain.

And you solve that by passing the `logCallback` and `maxLogLevel` unconditionally to smoldot

**Comment by tomaka** [comment]
After the change in this repo we'd also need to update the `ScProvider` as well

**Comment by wirednkod** [comment]
> After the change in this repo we'd also need to update the `ScProvider` as well

This is done [here](https://github.com/polkadot-js/api/pull/4796/)

**Comment by wirednkod** [comment]
This issue can close as #1027 is merged

**Comment by tomaka** [comment]
We still need to add the option to the public API
Right now it's still not possible to do this, from a pragmatic standpoint, to set this max log level when using PolkadotJS
