### ISSUE TITLE
Upgrade to latest yarn

### ISSUE THREAD

**Issue by raoulmillais** [paritytech/substrate-connect#972]
Most projects in parity are using the newest yarn and so is polkadotjs .. being on the same package manager makes life easier it's one less thing to think about when working with multiple projects locally

**Comment by wirednkod** [comment]
Side note: yarn v3 probably has some compatibility issues with [eslint](https://github.com/yarnpkg/berry/issues/8). It seems like there is some workaround - it is just not a trivial one
