### ISSUE TITLE
Add bootnodes functionality API and save in extension localstorage

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#981]

**Comment by tomaka** [comment]
Modifying a bootnode from the UI should call a method in the `Background` interface in `index.ts`, and it's `index.ts` that handles the logic

**Comment by wirednkod** [comment]
cc #492

**Comment by wirednkod** [comment]
Fixed with #1079

**Comment by tomaka** [comment]
You didn't add methods to add/remove bootnodes
